# Minimal docker internal networking test
services:
  attacker:
    build: ./attacker
    container_name: attacker
  target:
    build: ./target
    container_name: target
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pw123
    container_name: database
networks:
  default:
      internal: true


