include:
  - targets/${TARGET:-juiceshop}/target.yml

services:
  executor:
    build: ./executor
    volumes:
      - target-src:/target-src:ro
    networks:
      - exposed
    depends_on: # Required for `docker compose up --wait` to not block infinitely when src-fetch has already exited
      src-fetch:
        condition: service_completed_successfully
        required: false

  threat-modeler:
    build: ./threat-modeler
    volumes:
      - target-src:/target-src:ro
    depends_on: # Required for `docker compose up --wait` to not block infinitely when src-fetch has already exited
      src-fetch:
        condition: service_completed_successfully
        required: false
networks:
  exposed:
    internal: true
  closed:
    internal: true

volumes:
  target-src:
    name: ${TARGET:-juiceshop}-target-src
