services:
  juiceshop:
    image: bkimminich/juice-shop:v19.2.1
    networks:
      - exposed

  src-fetch:
    image: alpine/git
    entrypoint: ["/bin/sh", "-c"]
    command: ["git clone --depth=1 --branch=v19.2.1 https://github.com/juice-shop/juice-shop.git /src"]
    volumes:
      - target-src:/src

volumes:
  target-src:
